force_torque:
  left_fingertip:
    sensor_joint: gripper_finger_joint
    frame: gripper_left_fingertip_link
  right_fingertip:
    sensor_joint: gripper_right_finger_joint
    frame: gripper_right_fingertip_link

imu:
  base_imu:
    frame: base_imu_link
    gazebo_sensor_name: imu_sensor
